Check state dir
vrtdev/aws_lifecycle_hooks pull request #2
Opened 2019-07-01 11:45 UTC by zipkid

2019-07-01 11:53 UTC, nielslaukens requested changes

2019-07-01 11:53 UTC, nielslaukens commented on files/aws_lifecycle_hooks/set_inservice.py
> +            statefile_h = open(os.path.join(r + '/' + statefile), 'r')
in python doe je meestal
```
with open(f, "r") as file:
    state = file.read()
```

Want hier vergeet je je files te sluiten...

2019-07-01 11:53 UTC, nielslaukens commented on files/aws_lifecycle_hooks/set_inservice.py
> +    import os
import bovenaan zetten. `os` is toch stdlib, dus dat is er altijd

2019-07-02 06:49 UTC, jhooyberghs approved these changes

2019-07-02 06:57 UTC, merged